# Generated by Django 4.2.30 on 2026-04-16 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0015_attendancelockperiod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Locked', 'Locked')], default='Draft', max_length=16)),
                ('per_day_rate_used', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('per_hour_ot_rate_used', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_hours_per_day', models.DecimalField(decimal_places=2, default=8, max_digits=5)),
                ('days_present', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('days_late', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('days_half', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('days_leave', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('days_absent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('holiday_work_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('ot_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('regular_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ot_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('holiday_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('leave_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('allowance_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deduction_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('basic_for_epf', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('epf_employee_pct', models.DecimalField(decimal_places=2, default=8, max_digits=5)),
                ('epf_company_pct', models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ('etf_company_pct', models.DecimalField(decimal_places=2, default=3, max_digits=5)),
                ('epf_employee_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('epf_company_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('etf_company_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_vouchers', to='main.employee')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers_generated', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers_locked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_end', '-generated_at'],
                'unique_together': {('employee', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='VoucherDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='calculation.paymentvoucher')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='calculation.paymentvoucher')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_day_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('per_hour_ot_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_hours_per_day', models.DecimalField(decimal_places=2, default=8, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_profile', to='main.employee')),
            ],
        ),
    ]
