# Generated by Django 4.2.30 on 2026-04-16 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0015_attendancelockperiod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FingerprintUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Staged', 'Staged'), ('Committed', 'Committed'), ('Reverted', 'Reverted')], default='Staged', max_length=16)),
                ('total_rows', models.IntegerField(default=0)),
                ('matched_rows', models.IntegerField(default=0)),
                ('ambiguous_rows', models.IntegerField(default=0)),
                ('unmatched_rows', models.IntegerField(default=0)),
                ('conflict_rows', models.IntegerField(default=0)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('committed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fingerprint_commits', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fingerprint_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FingerprintRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, default='', max_length=255)),
                ('raw_name', models.CharField(blank=True, default='', max_length=255)),
                ('parsed_empcode', models.CharField(blank=True, default='', max_length=50)),
                ('parsed_name', models.CharField(blank=True, default='', max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('shift', models.CharField(blank=True, default='', max_length=100)),
                ('time_period', models.CharField(blank=True, default='', max_length=100)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('match_status', models.CharField(choices=[('Matched', 'Matched'), ('Ambiguous', 'Ambiguous'), ('Unmatched', 'Unmatched'), ('Manual', 'Manual')], default='Unmatched', max_length=16)),
                ('has_asm_conflict', models.BooleanField(default=False)),
                ('skip_commit', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('committed_attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fingerprint_rows', to='main.attendance')),
                ('matched_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fingerprint_rows', to='main.employee')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='fingerprint.fingerprintupload')),
            ],
            options={
                'ordering': ['date', 'raw_name'],
            },
        ),
    ]
