# Generated by Django 5.2 on 2025-04-03 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_photo', models.URLField(blank=True, null=True)),
                ('date_of_birth', models.DateField()),
                ('designation', models.CharField(max_length=255)),
                ('agency', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmpLeave',
            fields=[
                ('leave_refno', models.AutoField(primary_key=True, serialize=False)),
                ('leave_date', models.DateField()),
                ('leave_day', models.CharField(max_length=10)),
                ('leave_type', models.CharField(max_length=50)),
                ('agency', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_location_code', models.CharField(blank=True, max_length=100, null=True)),
                ('add_type', models.CharField(max_length=50)),
                ('add_date', models.DateField(auto_now_add=True)),
                ('confirm_date', models.DateField(blank=True, null=True)),
                ('confirm_done', models.BooleanField(default=False)),
                ('remove_done', models.BooleanField(default=False)),
                ('remove_date', models.DateField(blank=True, null=True)),
                ('hcode', models.CharField(blank=True, max_length=20, null=True)),
                ('max_day_off', models.IntegerField(default=0)),
                ('add_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_added_by', to=settings.AUTH_USER_MODEL)),
                ('confirm_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_confirmed_by', to=settings.AUTH_USER_MODEL)),
                ('remove_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_removed_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('check_in_time', models.DateTimeField()),
                ('check_in_lat', models.FloatField()),
                ('check_in_long', models.FloatField()),
                ('photo_check_in', models.URLField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_lat', models.FloatField(blank=True, null=True)),
                ('check_out_long', models.FloatField(blank=True, null=True)),
                ('photo_check_out', models.URLField(blank=True, null=True)),
                ('worked_hours', models.FloatField(blank=True, null=True)),
                ('ot_hours', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius_meters', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_agencies', to='main.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius_meters', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.agency')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outlet_manager', to='main.employee')),
            ],
        ),
    ]
