# Generated by Django 5.2 on 2025-04-05 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_outlet_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='designation',
        ),
    ]
