# Generated by Django 5.2 on 2025-04-05 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_employee_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hcode', models.CharField(max_length=50, unique=True)),
                ('holiday_name', models.CharField(max_length=255)),
                ('holiday_type', models.CharField(max_length=50)),
                ('holiday_type_name', models.CharField(max_length=100)),
                ('hdate', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('holiday_ot_pay_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('holiday_regular_pay_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'holiday',
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('att_type', models.CharField(max_length=50, unique=True)),
                ('att_type_name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('att_type_group', models.CharField(max_length=100)),
                ('att_type_per_day_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pay_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('att_type_no_of_days_in_year', models.IntegerField()),
                ('year_start_date', models.DateField()),
                ('year_end_date', models.DateField()),
            ],
            options={
                'db_table': 'leave_type',
            },
        ),
        migrations.RemoveField(
            model_name='agency',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='radius_meters',
        ),
        migrations.RemoveField(
            model_name='empleave',
            name='add_type',
        ),
        migrations.AlterField(
            model_name='empleave',
            name='hcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.holiday'),
        ),
        migrations.AlterField(
            model_name='empleave',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.leavetype'),
        ),
    ]
