# Generated by Django 5.2 on 2025-04-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='outlet',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
    ]
