# Generated by Django 4.2.23 on 2026-04-15 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_alter_attendance_options_attendance_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', 'employee']},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='empleave',
            name='add_user',
        ),
        migrations.RemoveField(
            model_name='empleave',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='empleave',
            name='confirm_date',
        ),
        migrations.RemoveField(
            model_name='empleave',
            name='confirm_done',
        ),
        migrations.RemoveField(
            model_name='empleave',
            name='confirm_user',
        ),
        migrations.RemoveField(
            model_name='empleave',
            name='hcode',
        ),
        migrations.RemoveField(
            model_name='empleave',
            name='leave_day',
        ),
        migrations.RemoveField(
            model_name='empleave',
            name='max_day_off',
        ),
        migrations.RemoveField(
            model_name='empleave',
            name='primary_location_code',
        ),
        migrations.RemoveField(
            model_name='empleave',
            name='remove_date',
        ),
        migrations.RemoveField(
            model_name='empleave',
            name='remove_done',
        ),
        migrations.RemoveField(
            model_name='empleave',
            name='remove_user',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='outlet',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='attendance',
            name='punchin_verification',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='punchout_verification',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='empleave',
            name='action_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleave',
            name='action_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_actioned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empleave',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleave',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='basic_salary',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='cal_epf',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='empcode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employ_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='epf_cal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='epf_com_per',
            field=models.FloatField(blank=True, default=12.0, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='epf_emp_per',
            field=models.FloatField(blank=True, default=8.0, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='epf_grade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='epf_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='etf_com_per',
            field=models.FloatField(blank=True, default=3.0, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='idnumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='inactive_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='outlets',
            field=models.ManyToManyField(blank=True, related_name='employees', to='main.outlet'),
        ),
        migrations.AddField(
            model_name='employee',
            name='punchin_selfie',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.punchin_selfie_upload_path),
        ),
        migrations.AddField(
            model_name='employee',
            name='punchout_selfie',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.punchout_selfie_upload_path),
        ),
        migrations.AddField(
            model_name='employee',
            name='reference_photo',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.reference_photo_upload_path),
        ),
        migrations.AddField(
            model_name='outlet',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outlet_manager', to='main.employee'),
        ),
        migrations.AddField(
            model_name='outlet',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='verification_notes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='hcode',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='EmployeeStatusLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('DEACTIVATED', 'DEACTIVATED'), ('ACTIVATED', 'ACTIVATED')], max_length=20)),
                ('action_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, null=True)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_status_actions', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='main.employee')),
            ],
            options={
                'ordering': ['-action_at'],
            },
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('device_type', models.CharField(choices=[('personal', 'Personal'), ('company', 'Company')], max_length=50)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceEditRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('proposed_check_in', models.DateTimeField()),
                ('proposed_check_out', models.DateTimeField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='main.attendance')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_edit_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='photo_check_in',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='photo_check_out',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='verified',
        ),
    ]
