# Generated by Django 4.2.23 on 2026-04-15 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_fix_employee_fullname_empcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='primary_outlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_employees', to='main.outlet'),
        ),
    ]
