# Generated by Django 4.2.30 on 2026-04-16 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_employee_primary_outlet'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceModificationLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('original_date', models.DateField(blank=True, null=True)),
                ('original_check_in_time', models.DateTimeField(blank=True, null=True)),
                ('original_check_out_time', models.DateTimeField(blank=True, null=True)),
                ('original_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_date', models.DateField(blank=True, null=True)),
                ('new_check_in_time', models.DateTimeField(blank=True, null=True)),
                ('new_check_out_time', models.DateTimeField(blank=True, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Applied', max_length=16)),
                ('reason', models.TextField(blank=True, default='')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, default='')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modification_logs', to='main.attendance')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_mods_requested', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_mods_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
